export default {
    PEER_NOT_ONLINE: 'PEER_NOT_ONLINE',
    PEER_SOCKET_NOT_OPEN: 'PEER_SOCKET_NOT_OPEN',
    NEW_CONN_WITH_SAME_ID: 'NEW_CONN_WITH_SAME_ID',
    IP_CONN_RATE_LIMIT_EXCEEDED: 'IP_CONN_RATE_LIMIT_EXCEEDED',
    MESSAGE_RATE_LIMIT_EXCEEDED: 'MESSAGE_RATE_LIMIT_EXCEEDED',
};
