export default {
    ID_MIN_LENGTH_IS_4: 'ID_MIN_LENGTH_IS_4',
    PEER_ID_NOT_VALID: 'PEER_ID_NOT_VALID',
    PEER_NOT_ONLINE: 'PEER_NOT_ONLINE',
    PEER_SOCKET_NOT_OPEN: 'PEER_SOCKET_NOT_OPEN',
    NEW_CONN_WITH_SAME_ID: 'NEW_CONN_WITH_SAME_ID',
    IP_CONN_RATE_LIMIT_EXCEEDED: 'IP_CONN_RATE_LIMIT_EXCEEDED',
    MESSAGE_RATE_LIMIT_EXCEEDED: 'MESSAGE_RATE_LIMIT_EXCEEDED',
};
